---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/local/bin/python3.7

  collections:
    - awx.awx

  environment:
    TOWER_PASSWORD: "{{ lookup('file','/run/secrets/TOWER_PASSWORD') }}"
    TOWER_USERNAME: "{{ lookup('file','/run/secrets/TOWER_USERNAME') }}"

  tasks:
    - name: "Launch job {{ job }} in environment {{ project }}"
      tower_job_launch:
        job_template: "{{ project }} - {{ job }}"
        extra_vars:
          kolla_action: "{{ kolla_action|default('deploy') }}"
