---
name: Build docker image

"on":
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - scripts/*
  pull_request:
    paths:
      - .github/workflows/build-docker-image.yml
      - Containerfile
      - files/**
      - scripts/*

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        awx_version:
          - 19.0.0
          - 19.1.0
          - 19.2.0
          - 19.2.1
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.ref == 'refs/heads/main'
      - run: scripts/build.sh
        env:
          VERSION: ${{ matrix.awx_version }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/awxclient
      - run: |
          scripts/push.sh
        env:
          VERSION: ${{ matrix.awx_version }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          REPOSITORY: osism/awxclient
        if: github.ref == 'refs/heads/main'
